<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_56dedc26e5388',
    'title' => __('Social feed', 'modularity-testimonials'),
    'fields' => array(
        0 => array(
            'key' => 'field_5a16a733a14cb',
            'label' => __('Social media feeds', 'modularity-testimonials'),
            'name' => 'social_media_feeds',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                '5a16a8af5d177' => array(
                    'key' => '5a16a8af5d177',
                    'name' => 'facebook',
                    'label' => __('Facebook', 'modularity-testimonials'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5a16da3af91bf',
                            'label' => 'Facebook App ID',
                            'name' => 'mod_socialmedia_fb_app_id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5a16daf6f91c0',
                            'label' => 'Facebook App Secret',
                            'name' => 'mod_socialmedia_fb_app_secret',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5a16db13f91c1',
                            'label' => 'Facebook Username',
                            'name' => 'mod_socialmedia_fb_username',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '@',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5a16db42f91c2' => array(
                    'key' => '5a16db42f91c2',
                    'name' => 'instagram',
                    'label' => __('Instagram', 'modularity-testimonials'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5a16db4cf91c3',
                            'label' => 'Type of Feed',
                            'name' => 'mod_socialmedia_in_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'user' => 'User',
                                'hashtag' => 'Hashtag',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'user',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        1 => array(
                            'key' => 'field_5a16db95f91c4',
                            'label' => 'Instagram Username',
                            'name' => 'mod_socialmedia_in_username',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5a16db4cf91c3',
                                        'operator' => '==',
                                        'value' => 'user',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '@',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5a16dba4f91c5',
                            'label' => 'Instagram Hashtag',
                            'name' => 'mod_socialmedia_in_hashtag',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5a16db4cf91c3',
                                        'operator' => '==',
                                        'value' => 'hashtag',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '#',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'button_label' => __('Add new feed source', 'modularity-testimonials'),
            'min' => '',
            'max' => 10,
        ),
        1 => array(
            'key' => 'field_56dfe51e498cb',
            'label' => __('Max items', 'modularity-testimonials'),
            'name' => 'mod_social_items',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 10,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        2 => array(
            'key' => 'field_56e038fa40a78',
            'label' => __('Numer of columns', 'modularity-testimonials'),
            'name' => 'mod_social_columns',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 3,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        3 => array(
            'key' => 'field_59afbaef4019a',
            'label' => __('Add link', 'modularity-testimonials'),
            'name' => 'mod_social_link',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Check this box if you want to display a button that links to the social media page.', 'modularity-testimonials'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_59afbc492866a',
            'label' => __('Web adress', 'modularity-testimonials'),
            'name' => 'mod_social_link_url',
            'type' => 'url',
            'instructions' => __('Enter URL to a social media feed or page.', 'modularity-testimonials'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_59afbaef4019a',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        5 => array(
            'key' => 'field_59afbbaa061a7',
            'label' => __('Button text', 'modularity-testimonials'),
            'name' => 'mod_social_link_text',
            'type' => 'text',
            'instructions' => __('Enter button text.', 'modularity-testimonials'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_59afbaef4019a',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Gå till sida',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-socialmedia',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}